name: Run Parser at HH:02

on:
  schedule:
    - cron: '2 * * * *'  # Каждый час в :02 минуты (UTC)
  workflow_dispatch:     # Позволяет запускать вручную

permissions:
  contents: write       # Даем права на запись в репозиторий

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Parser
        run: python parser.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --ff-only  # Синхронизируем с удаленным репозиторием
          git add data.json   # Или другой файл, который изменяет парсер
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: New data from parser [skip ci]"
          
          git push
