name: Telegram Parser Auto-Run

on:
  schedule:
    - cron: '*/59 * * * *'  # Каждые 59 минут
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Dependencies installed"

      - name: Run parser
        run: |
          echo "Starting parser at $(date)"
          python parser.py
          echo "Parser finished with exit code $?"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"
          
          # Проверяем изменения
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git add .
            git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
            
            # Пытаемся сделать push с 3 попытками
            for i in {1..3}; do
              git pull --rebase origin main
              if git push origin main; then
                echo "Push successful"
                break
              else
                echo "Push attempt $i failed"
                sleep 5
              fi
            done
          fi
