name: Schedule Test
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут (для теста)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test schedule
        run: echo "🕒 Работает! Время: $(date)"
